### ISSUE TITLE
Validacion de JWT en los headers

### ISSUE THREAD

**Issue by Cesaraugp** [La-supremacia/newsletter-app-contacts-service#3]
# Una ayudita pal pana

La validación del JWT que viene en los headers la puedes hacer con este [middleware de JWT](https://github.com/gofiber/jwt). Te adjunto las referencias al microservicio de organizaciones donde ya lo implementé.
Install command: `go get github.com/golang-jwt/jwt/v4`

[Añadir el middleware a la app](https://github.com/La-supremacia/newsletter-app-organizations-service/blob/main/pkg/middleware/fiber_middleware.go)
[Usando los claims en una ruta](https://github.com/La-supremacia/newsletter-app-organizations-service/blob/be2756f6204b046a0a7e0932b3b63a7f453e6f24/pkg/controllers/controller.go#L22)
[jwt utils](https://github.com/La-supremacia/newsletter-app-organizations-service/blob/be2756f6204b046a0a7e0932b3b63a7f453e6f24/pkg/utils/jwt.go#L13)

### IMPORTANTE
* El `contextKey`que uses en la configuración del [middleware de jwt](https://github.com/La-supremacia/newsletter-app-organizations-service/blob/be2756f6204b046a0a7e0932b3b63a7f453e6f24/pkg/middleware/fiber_middleware.go#L21) debe ser igual al que uses para obtener los claims con el método `c.Locals("auth").(*jwt.Token)` en las [utils](https://github.com/La-supremacia/newsletter-app-organizations-service/blob/be2756f6204b046a0a7e0932b3b63a7f453e6f24/pkg/utils/jwt.go#L14)

**Comment by angeljsb** [comment]
Pensé que había cerrado esto en un commit
